In [1]:
import datetime as dt
import numpy as np
import os
import pandas as pd
import pandas_datareader as web

In [75]:
W_AR = pd.read_csv('Weighted_Adjacency/W_AR.csv',index_col=0)
W_OE = pd.read_csv('Weighted_Adjacency/W_OE.csv',index_col=0)
W_ET = pd.read_csv('Weighted_Adjacency/W_ET.csv',index_col=0)
W_TF = pd.read_csv('Weighted_Adjacency/W_TF.csv',index_col=0)
W_FC = pd.read_csv('Weighted_Adjacency/W_FC.csv',index_col=0) 
W_TwTo = pd.read_csv('Weighted_Adjacency/W_TwTo.csv',index_col=0)

In [76]:
W_OE

,MMM,ABT,ABBV,ABMD,ACN,ATVI,ADBE,AMD,AAP,AES,...,WLTW,WYNN,XEL,XLNX,XYL,YUM,ZBRA,ZBH,ZION,ZTS
MMM,1.000000,0.260492,0.0,0.159569,0.246344,0.224292,0.258373,0.233070,0.273362,0.162842,...,0.198686,0.182384,0.215243,0.280123,0.0,0.294945,0.233234,0.254796,0.344550,0.0
ABT,0.260492,1.000000,0.0,0.104688,0.124079,0.159638,0.141236,0.106865,0.189080,0.102160,...,0.181884,0.173549,0.232523,0.142686,0.0,0.214664,0.101975,0.243019,0.229441,0.0
ABBV,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
ABMD,0.159569,0.104688,0.0,1.000000,0.167691,0.130741,0.177567,0.159438,0.147160,0.108051,...,0.113981,0.167679,0.093112,0.202387,0.0,0.133141,0.164233,0.120995,0.150947,0.0
ACN,0.246344,0.124079,0.0,0.167691,1.000000,0.181155,0.237084,0.232429,0.178047,0.139453,...,0.151679,0.155033,0.126202,0.293064,0.0,0.176149,0.190026,0.165447,0.208099,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YUM,0.294945,0.214664,0.0,0.133141,0.176149,0.219705,0.200469,0.178983,0.309509,0.158486,...,0.160244,0.270867,0.224847,0.197182,0.0,1.000000,0.221815,0.219109,0.266648,0.0
ZBRA,0.233234,0.101975,0.0,0.164233,0.190026,0.237980,0.310714,0.265113,0.253257,0.181326,...,0.184669,0.204773,0.160838,0.333309,0.0,0.221815,1.000000,0.178567,0.241821,0.0
ZBH,0.254796,0.243019,0.0,0.120995,0.165447,0.171127,0.212326,0.128585,0.173767,0.105465,...,0.180916,0.142857,0.151104,0.184187,0.0,0.219109,0.178567,1.000000,0.259793,0.0
ZION,0.344550,0.229441,0.0,0.150947,0.208099,0.218574,0.247283,0.185509,0.294412,0.165928,...,0.217703,0.210387,0.264209,0.278559,0.0,0.266648,0.241821,0.259793,1.000000,0.0
ZTS,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0

In [77]:
W_AR.values[[np.arange(W_AR.shape[0])]*2] = 1 #Forcing the diagonal to be 1 since we set all NaN's to 0
W_AR.where(W_AR <= .6, 1,inplace=True) #If its greater than .6 replace with 1
W_AR.where(W_AR == 1, 0,inplace=True)  #If it doest equal 1 replace with 0
A_AR = W_AR

W_OE.values[[np.arange(W_OE.shape[0])]*2] = 1 #Forcing the diagonal to be 1 since we set all NaN's to 0
W_OE.where(W_OE <= .6, 1,inplace=True)
W_OE.where(W_OE == 1, 0,inplace=True)
A_OE = W_OE

W_ET.values[[np.arange(W_ET.shape[0])]*2] = 1 #Forcing the diagonal to be 1 since we set all NaN's to 0
W_ET.where(W_ET <= .6, 1,inplace=True)
W_ET.where(W_ET == 1, 0,inplace=True)
A_ET = W_ET

W_TF.values[[np.arange(W_TF.shape[0])]*2] = 1 #Forcing the diagonal to be 1 since we set all NaN's to 0
W_TF.where(W_TF <= .6, 1,inplace=True)
W_TF.where(W_TF == 1, 0,inplace=True)
A_TF = W_TF

W_FC.values[[np.arange(W_FC.shape[0])]*2] = 1 #Forcing the diagonal to be 1 since we set all NaN's to 0
W_FC.where(W_FC <= .6, 1,inplace=True)
W_FC.where(W_FC == 1, 0,inplace=True)
A_FC = W_FC

W_TwTo.values[[np.arange(W_TwTo.shape[0])]*2] = 1 #Forcing the diagonal to be 1 since we set all NaN's to 0
W_TwTo.where(W_TwTo <= .6, 1,inplace=True)
W_TwTo.where(W_TwTo == 1, 0,inplace=True)
A_TwTo = W_TwTo

<ipython-input-77-b52c53b9e8e5>:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  W_AR.values[[np.arange(W_AR.shape[0])]*2] = 1 #Forcing the diagonal to be 1 since we set all NaN's to 0
<ipython-input-77-b52c53b9e8e5>:6: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  W_OE.values[[np.arange(W_OE.shape[0])]*2] = 1 #Forcing the diagonal to be 1 since we set all NaN's to 0
<ipython-input-77-b52c53b9e8e5>:11: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  W_ET.values[[np.arange(W_ET.shape[0])]*2] = 1 #Forcing the diagonal to be 1 since we set all NaN's to 0
<ipython-input-77-b52c53b9e8e5>:16: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  W_TF.values[[np.arange(W_TF.shape[0])]*2] = 1 #Forcing the diagonal to be 1 since we set all NaN's to 0
<ipython-input-77-b52c53b9e8e5>:21: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  W_FC.values[[np.arange(W_FC.shape[0])]*2] = 1 #Forcing the diagonal to be 1 since we set all NaN's to 0
<ipython-input-77-b52c53b9e8e5>:26: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  W_TwTo.values[[np.arange(W_TwTo.shape[0])]*2] = 1 #Forcing the diagonal to be 1 since we set all NaN's to 0

In [78]:
A_OE

,MMM,ABT,ABBV,ABMD,ACN,ATVI,ADBE,AMD,AAP,AES,...,WLTW,WYNN,XEL,XLNX,XYL,YUM,ZBRA,ZBH,ZION,ZTS
MMM,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ABT,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ABBV,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ABMD,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YUM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
ZBRA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
ZBH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
ZION,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
ZTS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [79]:
if not os.path.exists('Adjacency'):
    os.makedirs('Adjacency')

A_AR.to_csv('Adjacency/A_AR.csv')
A_OE.to_csv('Adjacency/A_OE.csv') 
A_ET.to_csv('Adjacency/A_ET.csv') 
A_TF.to_csv('Adjacency/A_TF.csv') 
A_FC.to_csv('Adjacency/A_FC.csv') 
A_TwTo.to_csv('Adjacency/A_TwTo.csv')